name: 'Polarify'
description: 'Legacy Polar Action — Please migrate to polarsource/actions/ads'

branding:
  icon: dollar-sign
  color: blue

inputs:
  path:
    description: 'Glob pattern of files fo run Polarify on'
    default: "**/*.md"
    required: true

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        echo "::warning title=Deprecated action::This Polar action is deprecated, please migrate to polarsource/actions/ads"
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Run
      run: |
        pip install uv
        uv run ${{ github.action_path }}/../ads/script.py ${{ inputs.path }}
      shell: bash
