name: Ads sync example

on:
  push:
    branches: ["main"]

  schedule:
    - cron: "0 7 * * *"

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: polarsource/actions/auth@main
        id: polar
        with:
          scope: 'openid'

      - name: Sync Polar ads
        uses: polarsource/actions/ads@main
        with:
          path: ads/demo.md
          token: ${{ steps.polar.outputs.token }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Polar ads
